name: Release ALG ISO

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    permissions:
      contents: write

    container:
      image: archlinux:latest
      options: --privileged

    steps:
      - uses: actions/checkout@v4

      - name: Set current date as environment variable
        run: echo "DATE=`date +'%Y.%m.%d'`" >>$GITHUB_ENV

      - name: Synchronise package repositories and install archiso
        run: |
          pacman-key --init
          pacman-key --recv-key 3056513887B78AEB --keyserver keyserver.ubuntu.com
          pacman-key --lsign-key 3056513887B78AEB
          pacman -U --noconfirm 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-keyring.pkg.tar.zst'
          pacman -U --noconfirm 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-mirrorlist.pkg.tar.zst'
          echo -e "\n[chaotic-aur]\nInclude = /etc/pacman.d/chaotic-mirrorlist"
          pacman -Syu --noconfirm archiso git archlinux-keyring wget reflector --needed

      - name: Running Reflector
        run: |
          reflector --country "France,Sweden" \
          --verbose \
          --sort rate \
          --protocol https \
          --latest 5 \
          --save /etc/pacman.d/mirrorlist
          pacman -Syu

      - name: Building TCET Linux ISO
        run: |
            ls -al
            pacman -Syu
            wget https://raw.githubusercontent.com/harshau007/arch-linux-gui-plasma/main/pacman.conf -O /etc/pacman.conf
            mkarchiso -v -w ./work -o ./out ./
            echo "ISO Built in ./out folder!"
            ls -al

      - name: Generating Checksum
        run: |
          ls -al
          cd out/
          touch checksum
          sha256sum  *.iso > checksum
          ls -al

      - name: Release ISO File
        uses: ncipollo/release-action@v1
        with:
            artifacts: "out/*.iso,out/checksum"
            body: "v2.0.0"
            generateReleaseNotes: false
            name: "TCET-Linux"
            tag: ${{ env.DATE }}